const genralFieldOptions = [
    { id: 1, name: "Software Engineering" },
    { id: 2, name: "Data Science" },
    { id: 3, name: "AI Developer" },
    { id: 4, name: "Machine Learning Engineer" },
    { id: 5, name: "Cloud Computing" },
    { id: 6, name: "DevOps Engineer" },
    { id: 7, name: "Cybersecurity Specialist" },
    { id: 8, name: "Blockchain Developer" },
    { id: 9, name: "UI/UX Designer" },
    { id: 10, name: "Product Manager (Tech)" },
    { id: 11, name: "Full Stack Developer" },
    { id: 12, name: "Frontend Developer" },
    { id: 13, name: "Backend Developer" },
    { id: 14, name: "Mobile App Developer" },
    { id: 15, name: "Data Engineer" },
    { id: 16, name: "Data Analyst" },
    { id: 17, name: "QA Engineer" },
    { id: 18, name: "Systems Architect" },
    { id: 19, name: "Network Engineer" },
    { id: 20, name: "IT Support Specialist" },
    { id: 21, name: "Database Administrator" },
    { id: 22, name: "Cloud Solutions Architect" },
    { id: 23, name: "Cybersecurity Analyst" },
    { id: 24, name: "AI Research Scientist" },
    { id: 25, name: "IoT Developer" },
    { id: 26, name: "Robotics Engineer" },
    { id: 27, name: "Augmented Reality (AR) Developer" },
    { id: 28, name: "Virtual Reality (VR) Developer" },
    { id: 29, name: "Other" },
];

export default genralFieldOptions