const durationOptions = [
    { label: "Short-term (a few weeks)", value: "Short-term (a few weeks)" },
    { label: "Long-term (a few months)", value: "Long-term (a few months)" },
  ];
  
  const teamSizeOptions = [
    { label: "Individual", value: "Individual" },
    { label: "Small Team (2-3 members)", value: "Small Team (2-3 members)" },
    { label: "Large Team (4+ members)", value: "Large Team (4+ members)" },
  ];
  
  const expectedOutcomeOptions = [
    { label: "Working Prototype", value: "Working Prototype" },
    { label: "Research Paper", value: "Research Paper" },
    { label: "Open-Source Contribution", value: "Open-Source Contribution" },
    { label: "Startup Idea", value: "Startup Idea" },
  ];

  const complexityLevelOptions = [
    { value: "Beginner", label: "Beginner" },
    { value: "Intermediate", label: "Intermediate" },
    { value: "Advanced", label: "Advanced" },
]


  const focusAreaOptions = [
    { value: "ai", label: "Artificial Intelligence" },
    { value: "web-development", label: "Web Development" },
    { value: "mobile-development", label: "Mobile Development" },
    { value: "data-science", label: "Data Science" },
    { value: "cybersecurity", label: "Cybersecurity" },
    { value: "embedded-systems", label: "Embedded Systems" },
    { value: "blockchain", label: "Blockchain" },
    { value: "cloud-computing", label: "Cloud Computing" },
    { value: "robotics", label: "Robotics" },
    { value: "iot", label: "Internet of Things (IoT)" },
    { value: "machine-learning", label: "Machine Learning" },
    { value: "natural-language-processing", label: "Natural Language Processing" },
    { value: "computer-vision", label: "Computer Vision" },
    { value: "augmented-reality", label: "Augmented Reality (AR)" },
    { value: "virtual-reality", label: "Virtual Reality (VR)" },
    { value: "quantum-computing", label: "Quantum Computing" },
    { value: "edge-computing", label: "Edge Computing" },
    { value: "big-data", label: "Big Data" },
    { value: "autonomous-vehicles", label: "Autonomous Vehicles" },
    { value: "fintech", label: "Financial Technology (Fintech)" },
    { value: "biotechnology", label: "Biotechnology" },
    { value: "genomics", label: "Genomics" },
    { value: "health-informatics", label: "Health Informatics" },
    { value: "renewable-energy", label: "Renewable Energy" },
    { value: "smart-cities", label: "Smart Cities" },
    { value: "human-computer-interaction", label: "Human-Computer Interaction" },
    { value: "devops", label: "DevOps" },
    { value: "game-development", label: "Game Development" },
    { value: "e-commerce", label: "E-commerce" },
    { value: "social-networking", label: "Social Networking" },
    { value: "digital-twins", label: "Digital Twins" },
    { value: "3d-printing", label: "3D Printing" },
    { value: "wearable-technology", label: "Wearable Technology" },
    { value: "voice-recognition", label: "Voice Recognition" },
    { value: "ethical-ai", label: "Ethical AI" },
    { value: "education-technology", label: "Education Technology (EdTech)" },
    { value: "augmented-analytics", label: "Augmented Analytics" },
    { value: "supply-chain-management", label: "Supply Chain Management" },
    { value: "predictive-analytics", label: "Predictive Analytics" },
    { value: "digital-marketing", label: "Digital Marketing" },
    { value: "smart-manufacturing", label: "Smart Manufacturing" },
    { value: "network-security", label: "Network Security" },
    { value: "agritech", label: "Agriculture Technology (AgriTech)" },
    { value: "video-processing", label: "Video Processing" },
    { value: "mobile-security", label: "Mobile Security" },
    { value: "environmental-monitoring", label: "Environmental Monitoring" },
    { value: "database-management", label: "Database Management" },
    { value: "api-development", label: "API Development" },
    { value: "software-testing", label: "Software Testing" },
    { value: "crm-systems", label: "Customer Relationship Management (CRM) Systems" },
    { value: "erp-systems", label: "Enterprise Resource Planning (ERP) Systems" },
];

  
  const toolsAndTechnologies = [
    { label: "Python", value: "Python" },
    { label: "JavaScript", value: "JavaScript" },
    { label: "Java", value: "Java" },
    { label: "C++", value: "C++" },
    { label: "C#", value: "C#" },
    { label: "Ruby", value: "Ruby" },
    { label: "PHP", value: "PHP" },
    { label: "Swift", value: "Swift" },
    { label: "Go", value: "Go" },
    { label: "TypeScript", value: "TypeScript" },
    { label: "HTML", value: "HTML" },
    { label: "CSS", value: "CSS" },
    { label: "SQL", value: "SQL" },
    { label: "NoSQL", value: "NoSQL" },
    { label: "MongoDB", value: "MongoDB" },
    { label: "PostgreSQL", value: "PostgreSQL" },
    { label: "MySQL", value: "MySQL" },
    { label: "SQLite", value: "SQLite" },
    { label: "OracleDB", value: "OracleDB" },
    { label: "Redis", value: "Redis" },
    { label: "React", value: "React" },
    { label: "Angular", value: "Angular" },
    { label: "Vue.js", value: "Vue.js" },
    { label: "Node.js", value: "Node.js" },
    { label: "Express.js", value: "Express.js" },
    { label: "Django", value: "Django" },
    { label: "Flask", value: "Flask" },
    { label: "Ruby on Rails", value: "Ruby on Rails" },
    { label: "Spring Boot", value: "Spring Boot" },
    { label: "ASP.NET", value: "ASP.NET" },
    { label: "TensorFlow", value: "TensorFlow" },
    { label: "PyTorch", value: "PyTorch" },
    { label: "Keras", value: "Keras" },
    { label: "OpenCV", value: "OpenCV" },
    { label: "Scikit-learn", value: "Scikit-learn" },
    { label: "Pandas", value: "Pandas" },
    { label: "NumPy", value: "NumPy" },
    { label: "Matplotlib", value: "Matplotlib" },
    { label: "Seaborn", value: "Seaborn" },
    { label: "AWS", value: "AWS" },
    { label: "Azure", value: "Azure" },
    { label: "Google Cloud Platform (GCP)", value: "Google Cloud Platform (GCP)" },
    { label: "Docker", value: "Docker" },
    { label: "Kubernetes", value: "Kubernetes" },
    { label: "Terraform", value: "Terraform" },
    { label: "Ansible", value: "Ansible" },
    { label: "Jenkins", value: "Jenkins" },
    { label: "Git", value: "Git" },
    { label: "GitHub", value: "GitHub" },
    { label: "GitLab", value: "GitLab" },
    { label: "Bitbucket", value: "Bitbucket" },
    { label: "JIRA", value: "JIRA" },
    { label: "Confluence", value: "Confluence" },
    { label: "Slack", value: "Slack" },
    { label: "Trello", value: "Trello" },
    { label: "Visual Studio Code", value: "Visual Studio Code" },
    { label: "IntelliJ IDEA", value: "IntelliJ IDEA" },
    { label: "PyCharm", value: "PyCharm" },
    { label: "Eclipse", value: "Eclipse" },
    { label: "NetBeans", value: "NetBeans" },
    { label: "Xcode", value: "Xcode" },
    { label: "Android Studio", value: "Android Studio" },
    { label: "Unity", value: "Unity" },
    { label: "Unreal Engine", value: "Unreal Engine" },
    { label: "MATLAB", value: "MATLAB" },
    { label: "Simulink", value: "Simulink" },
    { label: "Blender", value: "Blender" },
    { label: "AutoCAD", value: "AutoCAD" },
    { label: "Figma", value: "Figma" },
    { label: "Sketch", value: "Sketch" },
    { label: "Adobe Photoshop", value: "Adobe Photoshop" },
    { label: "Adobe Illustrator", value: "Adobe Illustrator" },
    { label: "Inkscape", value: "Inkscape" },
    { label: "Bootstrap", value: "Bootstrap" },
    { label: "Tailwind CSS", value: "Tailwind CSS" },
    { label: "SASS", value: "SASS" },
    { label: "LESS", value: "LESS" },
    { label: "Webpack", value: "Webpack" },
    { label: "Babel", value: "Babel" },
    { label: "Nginx", value: "Nginx" },
    { label: "Apache", value: "Apache" },
    { label: "Tomcat", value: "Tomcat" },
    { label: "IIS", value: "IIS" },
    { label: "Vagrant", value: "Vagrant" },
    { label: "VirtualBox", value: "VirtualBox" },
    { label: "VMware", value: "VMware" },
    { label: "Firebase", value: "Firebase" },
    { label: "Heroku", value: "Heroku" },
    { label: "Netlify", value: "Netlify" },
    { label: "Vercel", value: "Vercel" },
    { label: "Jupyter Notebook", value: "Jupyter Notebook" },
    { label: "R", value: "R" },
    { label: "MATLAB", value: "MATLAB" },
    { label: "SAS", value: "SAS" },
    { label: "SPSS", value: "SPSS" },
    { label: "Tableau", value: "Tableau" },
    { label: "Power BI", value: "Power BI" },
    { label: "QlikView", value: "QlikView" },
    { label: "Snowflake", value: "Snowflake" },
    { label: "Hadoop", value: "Hadoop" },
    { label: "Spark", value: "Spark" },
    { label: "Kafka", value: "Kafka" },
    { label: "Elasticsearch", value: "Elasticsearch" },
    { label: "Logstash", value: "Logstash" },
    { label: "Kibana", value: "Kibana" },
    { label: "Grafana", value: "Grafana" },
    { label: "Prometheus", value: "Prometheus" },
    { label: "Splunk", value: "Splunk" },
    { label: "Nagios", value: "Nagios" },
    { label: "Zabbix", value: "Zabbix" },
    { label: "Puppet", value: "Puppet" },
    { label: "Chef", value: "Chef" },
    { label: "SaltStack", value: "SaltStack" },
    { label: "CircleCI", value: "CircleCI" },
    { label: "Travis CI", value: "Travis CI" },
    { label: "TeamCity", value: "TeamCity" },
    { label: "Maven", value: "Maven" },
    { label: "Gradle", value: "Gradle" },
    { label: "Ant", value: "Ant" },
    { label: "Yarn", value: "Yarn" },
    { label: "npm", value: "npm" },
    { label: "Bower", value: "Bower" },
    { label: "Rust", value: "Rust" },
    { label: "Elixir", value: "Elixir" },
    { label: "Haskell", value: "Haskell" },
    { label: "Lua", value: "Lua" },
    { label: "Perl", value: "Perl" },
    { label: "COBOL", value: "COBOL" },
    { label: "Fortran", value: "Fortran" },
    { label: "Racket", value: "Racket" },
    { label: "F#", value: "F#" },
    { label: "Scala", value: "Scala" },
    { label: "Groovy", value: "Groovy" },
    { label: "Solidity", value: "Solidity" },
    { label: "Hyperledger", value: "Hyperledger" },
    { label: "Ethereum", value: "Ethereum" },
    { label: "Raspberry Pi", value: "Raspberry Pi" },
    { label: "Arduino", value: "Arduino" },
    { label: "ESP32", value: "ESP32" },
    { label: "Zigbee", value: "Zigbee" },
    { label: "Bluetooth", value: "Bluetooth" },
    { label: "Wi-Fi", value: "Wi-Fi" },
    { label: "5G", value: "5G" },
    { label: "LoRaWAN", value: "LoRaWAN" },
    { label: "MQTT", value: "MQTT" },
    { label: "ROS", value: "ROS" },
    { label: "LabVIEW", value: "LabVIEW" },
    { label: "Verilog", value: "Verilog" },
    { label: "VHDL", value: "VHDL" },
    { label: "FPGA", value: "FPGA" },
    { label: "PLC", value: "PLC" },
    { label: "SCADA", value: "SCADA" },
    { label: "OpenCV", value: "OpenCV" },
    { label: "Hadoop", value: "Hadoop" },
    { label: "Spark", value: "Spark" },
    { label: "TensorFlow", value: "TensorFlow" },
    { label: "Keras", value: "Keras" },
    { label: "Scikit-learn", value: "Scikit-learn" },
    { label: "PyTorch", value: "PyTorch" },
    { label: "Pandas", value: "Pandas" },
    { label: "NumPy", value: "NumPy" },
    { label: "Matplotlib", value: "Matplotlib" },
    { label: "Seaborn", value: "Seaborn" },
    { label: "NLTK", value: "NLTK" },
    { label: "SpaCy", value: "SpaCy" },
    { label: "Gensim", value: "Gensim" },
    { label: "Stanford NLP", value: "Stanford NLP" },
    { label: "CoreNLP", value: "CoreNLP" },
    { label: "Word2Vec", value: "Word2Vec" },
    { label: "BERT", value: "BERT" },
    { label: "GPT", value: "GPT" },
    { label: "Tesseract", value: "Tesseract" },
    { label: "YOLO", value: "YOLO" },
    { label: "OpenAI Gym", value: "OpenAI Gym" },
    { label: "Unity ML-Agents", value: "Unity ML-Agents" },
    { label: "Stable Baselines", value: "Stable Baselines" },
    { label: "DeepMind Lab", value: "DeepMind Lab" },
    { label: "AWS SageMaker", value: "AWS SageMaker" },
    { label: "Google AI Platform", value: "Google AI Platform" },
    { label: "Azure ML Studio", value: "Azure ML Studio" },
    { label: "Kubeflow", value: "Kubeflow" },
    { label: "MLflow", value: "MLflow" },
    { label: "Airflow", value: "Airflow" },
    { label: "Prefect", value: "Prefect" },
    { label: "Luigi", value: "Luigi" },
    { label: "Dagster", value: "Dagster" },
    { label: "Seldon", value: "Seldon" },
    { label: "TensorRT", value: "TensorRT" },
    { label: "ONNX", value: "ONNX" },
    { label: "Hugging Face Transformers", value: "Hugging Face Transformers" },
    { label: "DeepSpeech", value: "DeepSpeech" },
    { label: "Kaldi", value: "Kaldi" },
    { label: "CMU Sphinx", value: "CMU Sphinx" },
    { label: "FastAPI", value: "FastAPI" },
    { label: "Flask", value: "Flask" },
    { label: "Django", value: "Django" },
    { label: "Bottle", value: "Bottle" },
    { label: "Falcon", value: "Falcon" },
    { label: "Tornado", value: "Tornado" },
    { label: "Sanic", value: "Sanic" },
    { label: "Hug", value: "Hug" },
    { label: "PHP", value: "PHP" },
    { label: "Laravel", value: "Laravel" },
    { label: "Symfony", value: "Symfony" },
    { label: "Zend Framework", value: "Zend Framework" },
    { label: "CodeIgniter", value: "CodeIgniter" },
    { label: "CakePHP", value: "CakePHP" },
    { label: "Yii", value: "Yii" },
    { label: "WordPress", value: "WordPress" },
    { label: "Joomla", value: "Joomla" },
    { label: "Drupal", value: "Drupal" },
    { label: "Magento", value: "Magento" },
    { label: "PrestaShop", value: "PrestaShop" },
    { label: "OpenCart", value: "OpenCart" },
    { label: "BigCommerce", value: "BigCommerce" },
    { label: "Shopify", value: "Shopify" },
    { label: "Salesforce", value: "Salesforce" },
    { label: "Oracle CRM", value: "Oracle CRM" },
    { label: "SAP CRM", value: "SAP CRM" },
    { label: "Microsoft Dynamics CRM", value: "Microsoft Dynamics CRM" },
    { label: "Zoho CRM", value: "Zoho CRM" },
    { label: "HubSpot", value: "HubSpot" },
    { label: "Marketo", value: "Marketo" },
    { label: "Mailchimp", value: "Mailchimp" },
    { label: "SendGrid", value: "SendGrid" },
    { label: "Mandrill", value: "Mandrill" },
    { label: "Postman", value: "Postman" },
    { label: "Insomnia", value: "Insomnia" },
    { label: "Swagger", value: "Swagger" },
    { label: "GraphQL", value: "GraphQL" },
    { label: "Apollo", value: "Apollo" },
    { label: "Relay", value: "Relay" },
    { label: "Prisma", value: "Prisma" },
    { label: "Hasura", value: "Hasura" },
    { label: "Strapi", value: "Strapi" },
    { label: "Contentful", value: "Contentful" },
    { label: "WordPress", value: "WordPress" },
    { label: "Ghost", value: "Ghost" },
    { label: "Jekyll", value: "Jekyll" },
    { label: "Hugo", value: "Hugo" },
    { label: "Gatsby", value: "Gatsby" },
    { label: "Next.js", value: "Next.js" },
    { label: "Nuxt.js", value: "Nuxt.js" },
    { label: "Svelte", value: "Svelte" },
    { label: "Sapper", value: "Sapper" },
    { label: "Meteor", value: "Meteor" },
    { label: "Backbone.js", value: "Backbone.js" },
    { label: "Ember.js", value: "Ember.js" },
    { label: "Knockout.js", value: "Knockout.js" },
    { label: "Alpine.js", value: "Alpine.js" },
    { label: "Stimulus", value: "Stimulus" },
    { label: "Livewire", value: "Livewire" },
    { label: "Lumen", value: "Lumen" },
    { label: "Slim", value: "Slim" },
    { label: "PHPUnit", value: "PHPUnit" },
    { label: "Behat", value: "Behat" },
    { label: "Codeception", value: "Codeception" },
    { label: "Phinx", value: "Phinx" },
    { label: "Doctrine ORM", value: "Doctrine ORM" },
    { label: "Eloquent ORM", value: "Eloquent ORM" },
    { label: "ActiveRecord", value: "ActiveRecord" },
    { label: "Hibernate", value: "Hibernate" },
    { label: "JPA", value: "JPA" },
    { label: "MyBatis", value: "MyBatis" },
    { label: "Spring Data", value: "Spring Data" },
    { label: "Doctrine", value: "Doctrine" },
    { label: "Doctrine DBAL", value: "Doctrine DBAL" },
    { label: "Flyway", value: "Flyway" },
    { label: "Liquibase", value: "Liquibase" },
    { label: "Knex.js", value: "Knex.js" },
    { label: "Sequelize", value: "Sequelize" },
    { label: "Bookshelf.js", value: "Bookshelf.js" },
    { label: "Objection.js", value: "Objection.js" },
    { label: "Prisma", value: "Prisma" },
    { label: "TypeORM", value: "TypeORM" },
    { label: "Mongoose", value: "Mongoose" },
    { label: "MikroORM", value: "MikroORM" },
    { label: "Waterline", value: "Waterline" },
    { label: "Ruby", value: "Ruby" },
    { label: "Rails", value: "Rails" },
    { label: "Sinatra", value: "Sinatra" },
    { label: "Grape", value: "Grape" },
    { label: "Padrino", value: "Padrino" },
    { label: "Hanami", value: "Hanami" },
    { label: "NancyFX", value: "NancyFX" },
    { label: "ServiceStack", value: "ServiceStack" },
    { label: "FluentMigrator", value: "FluentMigrator" },
    { label: "Serilog", value: "Serilog" },
    { label: "NLog", value: "NLog" },
    { label: "Log4Net", value: "Log4Net" },
    { label: "Sentry", value: "Sentry" },
    { label: "Honeybadger", value: "Honeybadger" },
    { label: "Rollbar", value: "Rollbar" },
    { label: "Raygun", value: "Raygun" },
    { label: "New Relic", value: "New Relic" },
    { label: "AppDynamics", value: "AppDynamics" },
    { label: "Dynatrace", value: "Dynatrace" },
    { label: "Splunk", value: "Splunk" },
    { label: "Datadog", value: "Datadog" },
    { label: "SignalFx", value: "SignalFx" },
    { label: "Prometheus", value: "Prometheus" },
    { label: "Grafana", value: "Grafana" },
    { label: "ELK Stack", value: "ELK Stack" },
    { label: "Graylog", value: "Graylog" },
    { label: "Nagios", value: "Nagios" },
    { label: "Zabbix", value: "Zabbix" },
    { label: "Monit", value: "Monit" },
    { label: "AWS CloudWatch", value: "AWS CloudWatch" },
    { label: "Azure Monitor", value: "Azure Monitor" },
    { label: "Google Stackdriver", value: "Google Stackdriver" },
    { label: "Pingdom", value: "Pingdom" },
    { label: "PagerDuty", value: "PagerDuty" },
    { label: "VictorOps", value: "VictorOps" },
    { label: "OpsGenie", value: "OpsGenie" },
    { label: "UptimeRobot", value: "UptimeRobot" },
    { label: "Uptrends", value: "Uptrends" },
    { label: "Site24x7", value: "Site24x7" },
    { label: "StatusCake", value: "StatusCake" },
    { label: "Geckoboard", value: "Geckoboard" },
    { label: "Tableau", value: "Tableau" },
    { label: "QlikView", value: "QlikView" },
    { label: "Power BI", value: "Power BI" },
    { label: "Looker", value: "Looker" },
    { label: "Domo", value: "Domo" },
    { label: "Sisense", value: "Sisense" },
    { label: "Chartio", value: "Chartio" },
    { label: "Klipfolio", value: "Klipfolio" },
    { label: "Periscope Data", value: "Periscope Data" },
    { label: "Metabase", value: "Metabase" },
    { label: "Redash", value: "Redash" },
    { label: "Mode Analytics", value: "Mode Analytics" },
    { label: "Grow", value: "Grow" },
    { label: "RJMetrics", value: "RJMetrics" },
    { label: "Databox", value: "Databox" },
    { label: "GoodData", value: "GoodData" },
    { label: "Pentaho", value: "Pentaho" },
    { label: "SAP BusinessObjects", value: "SAP BusinessObjects" },
    { label: "Cognos", value: "Cognos" },
    { label: "MicroStrategy", value: "MicroStrategy" },
    { label: "Alteryx", value: "Alteryx" },
    { label: "SAS", value: "SAS" },
    { label: "SPSS", value: "SPSS" },
    { label: "Stata", value: "Stata" },
    { label: "Minitab", value: "Minitab" },
    { label: "RapidMiner", value: "RapidMiner" },
    { label: "KNIME", value: "KNIME" },
    { label: "DataRobot", value: "DataRobot" },
    { label: "H2O.ai", value: "H2O.ai" },
    { label: "Dataiku", value: "Dataiku" },
    { label: "Fivetran", value: "Fivetran" },
    { label: "Stitch", value: "Stitch" },
    { label: "Matillion", value: "Matillion" },
    { label: "Talend", value: "Talend" },
    { label: "Informatica", value: "Informatica" },
    { label: "IBM DataStage", value: "IBM DataStage" },
    { label: "Apache NiFi", value: "Apache NiFi" },
    { label: "Airbyte", value: "Airbyte" },
    { label: "dbt", value: "dbt" },
    { label: "Apache Kafka", value: "Apache Kafka" },
    { label: "Apache Flink", value: "Apache Flink" },
    { label: "Apache Storm", value: "Apache Storm" },
    { label: "Apache Samza", value: "Apache Samza" },
    { label: "Amazon Kinesis", value: "Amazon Kinesis" },
    { label: "Google Pub/Sub", value: "Google Pub/Sub" },
    { label: "Microsoft Event Hubs", value: "Microsoft Event Hubs" },
    { label: "Confluent", value: "Confluent" },
    { label: "Hazelcast", value: "Hazelcast" },
    { label: "Redis", value: "Redis" },
    { label: "RabbitMQ", value: "RabbitMQ" },
    { label: "ActiveMQ", value: "ActiveMQ" },
    { label: "ZeroMQ", value: "ZeroMQ" },
    { label: "NATS", value: "NATS" },
    { label: "Pulsar", value: "Pulsar" },
    { label: "RocketMQ", value: "RocketMQ" },
    { label: "HiveMQ", value: "HiveMQ" },
    { label: "Mosquitto", value: "Mosquitto" },
    { label: "VerneMQ", value: "VerneMQ" },
    { label: "Eclipse Hono", value: "Eclipse Hono" },
    { label: "EMQ X", value: "EMQ X" },
    { label: "Azure Event Grid", value: "Azure Event Grid" },
    { label: "AWS SQS", value: "AWS SQS" },
    { label: "AWS SNS", value: "AWS SNS" },
    { label: "Google Cloud Pub/Sub", value: "Google Cloud Pub/Sub" },
    { label: "Kafka Streams", value: "Kafka Streams" },
    { label: "KSQL", value: "KSQL" },
    { label: "Apache Beam", value: "Apache Beam" },
    { label: "Google Dataflow", value: "Google Dataflow" },
    { label: "Apache Airflow", value: "Apache Airflow" },
    { label: "Apache Oozie", value: "Apache Oozie" },
    { label: "Amazon Glue", value: "Amazon Glue" },
    { label: "Azure Data Factory", value: "Azure Data Factory" },
    { label: "Google Cloud Data Fusion", value: "Google Cloud Data Fusion" },
    { label: "Prefect", value: "Prefect" },
    { label: "Dagster", value: "Dagster" },
    { label: "Luigi", value: "Luigi" },
    { label: "Bonobo", value: "Bonobo" },
    { label: "ETLBox", value: "ETLBox" },
    { label: "Hudi", value: "Hudi" },
    { label: "Delta Lake", value: "Delta Lake" },
    { label: "Iceberg", value: "Iceberg" },
    { label: "Presto", value: "Presto" },
    { label: "Trino", value: "Trino" },
    { label: "Apache Druid", value: "Apache Druid" },
    { label: "ClickHouse", value: "ClickHouse" },
    { label: "Greenplum", value: "Greenplum" },
    { label: "Snowflake", value: "Snowflake" },
    { label: "BigQuery", value: "BigQuery" },
    { label: "Redshift", value: "Redshift" },
    { label: "Athena", value: "Athena" },
    { label: "Exasol", value: "Exasol" },
    { label: "Teradata", value: "Teradata" },
    { label: "Vertica", value: "Vertica" },
    { label: "Yellowbrick", value: "Yellowbrick" },
    { label: "MemSQL", value: "MemSQL" },
    { label: "CockroachDB", value: "CockroachDB" },
    { label: "NuoDB", value: "NuoDB" },
    { label: "Citus", value: "Citus" },
    { label: "YugabyteDB", value: "YugabyteDB" },
    { label: "TiDB", value: "TiDB" },
    { label: "CrateDB", value: "CrateDB" },
    { label: "ScyllaDB", value: "ScyllaDB" },
    { label: "TimescaleDB", value: "TimescaleDB" },
    { label: "QuestDB", value: "QuestDB" },
    { label: "InfluxDB", value: "InfluxDB" },
    { label: "Prometheus", value: "Prometheus" },
    { label: "VictoriaMetrics", value: "VictoriaMetrics" },
    { label: "Thanos", value: "Thanos" },
    { label: "Cortex", value: "Cortex" },
    { label: "Mimir", value: "Mimir" },
    { label: "OpenTSDB", value: "OpenTSDB" },
    { label: "Graphite", value: "Graphite" },
    { label: "MetricTank", value: "MetricTank" },
    { label: "AppDynamics", value: "AppDynamics" },
    { label: "Dynatrace", value: "Dynatrace" },
    { label: "New Relic", value: "New Relic" },
    { label: "Instana", value: "Instana" },
    { label: "LightStep", value: "LightStep" },
    { label: "Datadog", value: "Datadog" },
    { label: "SignalFx", value: "SignalFx" },
    { label: "Splunk", value: "Splunk" },
    { label: "Cloudflare", value: "Cloudflare" },
    { label: "Fastly", value: "Fastly" },
    { label: "Akamai", value: "Akamai" },
    { label: "AWS CloudFront", value: "AWS CloudFront" },
    { label: "Azure CDN", value: "Azure CDN" },
    { label: "Google Cloud CDN", value: "Google Cloud CDN" },
    { label: "Netlify", value: "Netlify" },
    { label: "Vercel", value: "Vercel" },
    { label: "Cloudflare Workers", value: "Cloudflare Workers" },
    { label: "Fastly Compute@Edge", value: "Fastly Compute@Edge" },
    { label: "AWS Lambda", value: "AWS Lambda" },
    { label: "Azure Functions", value: "Azure Functions" },
    { label: "Google Cloud Functions", value: "Google Cloud Functions" },
    { label: "OpenFaaS", value: "OpenFaaS" },
    { label: "Kubeless", value: "Kubeless" },
    { label: "Knative", value: "Knative" },
    { label: "Fission", value: "Fission" },
    { label: "OpenWhisk", value: "OpenWhisk" },
    { label: "Iron.io", value: "Iron.io" },
    { label: "Pulumi", value: "Pulumi" },
    { label: "Terraform", value: "Terraform" },
    { label: "CloudFormation", value: "CloudFormation" },
    { label: "CDK", value: "CDK" },
    { label: "Ansible", value: "Ansible" },
    { label: "Chef", value: "Chef" },
    { label: "Puppet", value: "Puppet" },
    { label: "SaltStack", value: "SaltStack" },
    { label: "Consul", value: "Consul" },
    { label: "Vault", value: "Vault" },
    { label: "Nomad", value: "Nomad" },
    { label: "Kubernetes", value: "Kubernetes" },
    { label: "OpenShift", value: "OpenShift" },
    { label: "Rancher", value: "Rancher" },
    { label: "Docker Swarm", value: "Docker Swarm" },
    { label: "Mesos", value: "Mesos" },
    { label: "DC/OS", value: "DC/OS" },
    { label: "GKE", value: "GKE" },
    { label: "EKS", value: "EKS" },
    { label: "AKS", value: "AKS" },
    { label: "Tanzu", value: "Tanzu" },
    { label: "Google Anthos", value: "Google Anthos" },
    { label: "AWS Outposts", value: "AWS Outposts" },
    { label: "Azure Stack", value: "Azure Stack" },
    { label: "VMware Cloud", value: "VMware Cloud" },
    { label: "IBM Cloud", value: "IBM Cloud" },
    { label: "Oracle Cloud", value: "Oracle Cloud" },
    { label: "SAP Cloud", value: "SAP Cloud" },
    { label: "Alibaba Cloud", value: "Alibaba Cloud" },
    { label: "Tencent Cloud", value: "Tencent Cloud" },
    { label: "Huawei Cloud", value: "Huawei Cloud" },
    { label: "Linode", value: "Linode" },
    { label: "DigitalOcean", value: "DigitalOcean" },
    { label: "Vultr", value: "Vultr" },
    { label: "OVHcloud", value: "OVHcloud" },
    { label: "Hetzner", value: "Hetzner" },
    { label: "Scaleway", value: "Scaleway" },
    { label: "UpCloud", value: "UpCloud" },
    { label: "Kamatera", value: "Kamatera" },
    { label: "UCloud", value: "UCloud" },
    { label: "StackPath", value: "StackPath" },
    { label: "EdgeCast", value: "EdgeCast" },
    { label: "MaxCDN", value: "MaxCDN" },
    { label: "KeyCDN", value: "KeyCDN" },
    { label: "CacheFly", value: "CacheFly" },
    { label: "CDN77", value: "CDN77" },
    { label: "G-Core Labs", value: "G-Core Labs" },
    { label: "Cloudimage", value: "Cloudimage" },
    { label: "Cloudinary", value: "Cloudinary" },
    { label: "Imgix", value: "Imgix" },
    { label: "Kraken.io", value: "Kraken.io" },
    { label: "TinyPNG", value: "TinyPNG" },
    { label: "JPEGmini", value: "JPEGmini" },
    { label: "ImageOptim", value: "ImageOptim" },
    { label: "MozJPEG", value: "MozJPEG" },
    { label: "Guetzli", value: "Guetzli" },
    { label: "OptiPNG", value: "OptiPNG" },
    { label: "AdvPNG", value: "AdvPNG" },
    { label: "Pngcrush", value: "Pngcrush" },
    { label: "Pngquant", value: "Pngquant" },
    { label: "WebP", value: "WebP" },
    { label: "JPEG XL", value: "JPEG XL" },
    { label: "AVIF", value: "AVIF" },
    { label: "FLIF", value: "FLIF" },
    { label: "Brotli", value: "Brotli" },
    { label: "Zopfli", value: "Zopfli" },
    { label: "LZMA", value: "LZMA" },
    { label: "LZ4", value: "LZ4" },
    { label: "Snappy", value: "Snappy" },
    { label: "Zstandard", value: "Zstandard" },
    { label: "Bzip2", value: "Bzip2" },
    { label: "Gzip", value: "Gzip" },
    { label: "XZ", value: "XZ" },
    { label: "7-Zip", value: "7-Zip" },
    { label: "WinRAR", value: "WinRAR" },
    { label: "PeaZip", value: "PeaZip" },
    { label: "Bandizip", value: "Bandizip" },
    { label: "Archiver", value: "Archiver" },
    { label: "Unarchiver", value: "Unarchiver" },
    { label: "Keka", value: "Keka" },
    { label: "p7zip", value: "p7zip" },
    { label: "ZPAQ", value: "ZPAQ" },
    { label: "LRZip", value: "LRZip" },
    { label: "LZIP", value: "LZIP" },
    { label: "LRZ", value: "LRZ" },
    { label: "LHA", value: "LHA" },
    { label: "ZOO", value: "ZOO" },
    { label: "ARC", value: "ARC" },
    { label: "ARJ", value: "ARJ" },
    { label: "CPIO", value: "CPIO" },
    { label: "ISO", value: "ISO" },
    { label: "DMG", value: "DMG" },
    { label: "TAR", value: "TAR" },
    { label: "XZ", value: "XZ" },
    { label: "DEB", value: "DEB" },
    { label: "RPM", value: "RPM" },
    { label: "PKG", value: "PKG" },
    { label: "MSI", value: "MSI" },
    { label: "NSIS", value: "NSIS" },
    { label: "Inno Setup", value: "Inno Setup" },
    { label: "Squirrel", value: "Squirrel" },
    { label: "InstallShield", value: "InstallShield" },
    { label: "WiX Toolset", value: "WiX Toolset" },
    { label: "Advanced Installer", value: "Advanced Installer" },
  ];

  export {expectedOutcomeOptions, durationOptions, teamSizeOptions, complexityLevelOptions, focusAreaOptions, toolsAndTechnologies}