const durationOptions = [
  { label: "Short-term (a few weeks)", value: "Short-term (a few weeks)" },
  { label: "Long-term (a few months)", value: "Long-term (a few months)" },
];

const teamSizeOptions = [
  { label: "Individual", value: "Individual" },
  { label: "Small Team (2-3 members)", value: "Small Team (2-3 members)" },
  { label: "Large Team (4+ members)", value: "Large Team (4+ members)" },
];

const expectedOutcomeOptions = [
  { label: "Working Prototype", value: "Working Prototype" },
  { label: "Research Paper", value: "Research Paper" },
  { label: "Final Year Project", value: "Final Year Project" },
  { label: "Open-Source Contribution", value: "Open-Source Contribution" },
  { label: "Startup Idea", value: "Startup Idea" },
];

const complexityLevelOptions = [
  { value: "Beginner", label: "Beginner" },
  { value: "Intermediate", label: "Intermediate" },
  { value: "Advanced", label: "Advanced" },
];

const focusAreaOptions = [
  { value: "ai", label: "Artificial Intelligence" },
  { value: "web-development", label: "Web Development" },
  { value: "mobile-development", label: "Mobile Development" },
  { value: "data-science", label: "Data Science" },
  { value: "cybersecurity", label: "Cybersecurity" },
  { value: "embedded-systems", label: "Embedded Systems" },
  { value: "blockchain", label: "Blockchain" },
  { value: "cloud-computing", label: "Cloud Computing" },
  { value: "robotics", label: "Robotics" },
  { value: "iot", label: "Internet of Things (IoT)" },
  { value: "machine-learning", label: "Machine Learning" },
  {
    value: "natural-language-processing",
    label: "Natural Language Processing",
  },
  { value: "computer-vision", label: "Computer Vision" },
  { value: "augmented-reality", label: "Augmented Reality (AR)" },
  { value: "virtual-reality", label: "Virtual Reality (VR)" },
  { value: "quantum-computing", label: "Quantum Computing" },
  { value: "edge-computing", label: "Edge Computing" },
  { value: "big-data", label: "Big Data" },
  { value: "autonomous-vehicles", label: "Autonomous Vehicles" },
  { value: "fintech", label: "Financial Technology (Fintech)" },
  { value: "biotechnology", label: "Biotechnology" },
  { value: "genomics", label: "Genomics" },
  { value: "health-informatics", label: "Health Informatics" },
  { value: "renewable-energy", label: "Renewable Energy" },
  { value: "smart-cities", label: "Smart Cities" },
  { value: "human-computer-interaction", label: "Human-Computer Interaction" },
  { value: "devops", label: "DevOps" },
  { value: "game-development", label: "Game Development" },
  { value: "e-commerce", label: "E-commerce" },
  { value: "social-networking", label: "Social Networking" },
  { value: "digital-twins", label: "Digital Twins" },
  { value: "3d-printing", label: "3D Printing" },
  { value: "wearable-technology", label: "Wearable Technology" },
  { value: "voice-recognition", label: "Voice Recognition" },
  { value: "ethical-ai", label: "Ethical AI" },
  { value: "education-technology", label: "Education Technology (EdTech)" },
  { value: "augmented-analytics", label: "Augmented Analytics" },
  { value: "supply-chain-management", label: "Supply Chain Management" },
  { value: "predictive-analytics", label: "Predictive Analytics" },
  { value: "digital-marketing", label: "Digital Marketing" },
  { value: "smart-manufacturing", label: "Smart Manufacturing" },
  { value: "network-security", label: "Network Security" },
  { value: "agritech", label: "Agriculture Technology (AgriTech)" },
  { value: "video-processing", label: "Video Processing" },
  { value: "mobile-security", label: "Mobile Security" },
  { value: "environmental-monitoring", label: "Environmental Monitoring" },
  { value: "database-management", label: "Database Management" },
  { value: "api-development", label: "API Development" },
  { value: "software-testing", label: "Software Testing" },
  {
    value: "crm-systems",
    label: "Customer Relationship Management (CRM) Systems",
  },
  { value: "erp-systems", label: "Enterprise Resource Planning (ERP) Systems" },
];

const toolsAndTechnologies = [
  { label: "Python", value: "Python" },
  { label: "JavaScript", value: "JavaScript" },
  { label: "Java", value: "Java" },
  { label: "C++", value: "C++" },
  { label: "C#", value: "C#" },
  { label: "TypeScript", value: "TypeScript" },
  { label: "SQL", value: "SQL" },
  { label: "React", value: "React" },
  { label: "Node.js", value: "Node.js" },
  { label: "Express.js", value: "Express.js" },
  { label: "Django", value: "Django" },
  { label: "Flask", value: "Flask" },
  { label: "TensorFlow", value: "TensorFlow" },
  { label: "PyTorch", value: "PyTorch" },
  { label: "AWS", value: "AWS" },
  { label: "Azure", value: "Azure" },
  {
    label: "Google Cloud Platform (GCP)",
    value: "Google Cloud Platform (GCP)",
  },
  { label: "Docker", value: "Docker" },
  { label: "Kubernetes", value: "Kubernetes" },
  { label: "Git", value: "Git" },
  { label: "GitHub", value: "GitHub" },
  { label: "Visual Studio Code", value: "Visual Studio Code" },
  { label: "Jupyter Notebook", value: "Jupyter Notebook" },
  { label: "HTML", value: "HTML" },
  { label: "CSS", value: "CSS" },
  { label: "MongoDB", value: "MongoDB" },
  { label: "PostgreSQL", value: "PostgreSQL" },
  { label: "MySQL", value: "MySQL" },
  { label: "Bootstrap", value: "Bootstrap" },
  { label: "Tailwind CSS", value: "Tailwind CSS" },
  { label: "Figma", value: "Figma" },
  { label: "Laravel", value: "Laravel" },
  { label: "FastAPI", value: "FastAPI" },
  { label: "Apache Kafka", value: "Apache Kafka" },
];

export {
  expectedOutcomeOptions,
  durationOptions,
  teamSizeOptions,
  complexityLevelOptions,
  focusAreaOptions,
  toolsAndTechnologies,
};
