export const categoryGroups = {
  All: ["All"],
  "Artificial Intelligence": [
    "AI",
    "AI, Image Processing",
    "AI, Social Media Analytics",
    "AI, Computer Vision",
    "AI, Web | Desktop Application",
    "Android Mobile Development, AI, Web | Desktop Application",
    "Android Mobile Development, AI",
    "AI, Sensor, Web | Desktop Application",
    "Sensor, AI, Security and Encryption",
    "Artificial Intelligence & ML, Data mining, Image Processing, Security and Encryption, Sensor, Web | Desktop Application",
    "Artificial Intelligence & ML, Data mining, Image Processing, Security and Encryption, Web | Desktop Application",
  ],
  "Data Science": [
    "Healthcare, Data Science",
    "Data Science, Smart City",
    "Data Science, Natural Language Processing",
    "Cloud Computing, Data Mining, Security and Encryption",
    "Cloud Computing, Data Mining",
    "Cloud Computing, Data Mining, Security and Encryption, Web | Desktop Application",
    "Cloud Computing, Data Mining, Parallel And Distributed System, Security and Encryption, Web | Desktop Application",
    "Artificial Intelligence & ML, Data mining, Image Processing, Security and Encryption, Sensor, Web | Desktop Application",
    "Artificial Intelligence & ML, Data mining, Image Processing, Security and Encryption, Web | Desktop Application",
  ],
  "Cloud Computing": [
    "Cloud Computing, Security and Encryption, Web | Desktop Application",
    "Cloud Computing, Networking, Parallel And Distributed System, Security and Encryption, Web | Desktop Application",
    "Cloud Computing, Web | Desktop Application",
    "Cloud Computing, Data Mining, Security and Encryption",
    "Cloud Computing, Data Mining",
    "Cloud Computing, Networking, Security and Encryption, Web | Desktop Application",
    "Cloud Computing, Data Mining, Security and Encryption, Web | Desktop Application",
    "Cloud Computing, Data Mining, Parallel And Distributed System, Security and Encryption, Web | Desktop Application",
    "Cloud Computing, Security and Encryption",
    "Cloud Computing",
    "IoT, Cloud Computing, Web | Desktop Application",
    "IoT, Image Processing, Cloud Computing",
  ],
  "Image Processing": [
    "AI, Image Processing",
    "Image Processing",
    "Image Processing, Security and Encryption",
    "Image Processing, AI",
    "Image Processing, AI, Web | Desktop Application",
    "Image Processing, AI, Security and Encryption",
    "IoT, Image Processing, Security and Encryption",
    "IoT, Image Processing, Cloud Computing",
  ],
  IoT: [
    "IoT, Image Processing, Cloud Computing",
    "IoT, AI, Web | Desktop Application",
    "IoT, Sensor, GPS-GSM",
    "IoT, Cloud Computing, Web | Desktop Application",
    "IoT, Image Processing, Security and Encryption",
    "IoT, Android Mobile Development, Web | Desktop Application",
    "IoT",
  ],
  "Security and Encryption": [
    "Cloud Computing, Security and Encryption, Web | Desktop Application",
    "Cloud Computing, Networking, Parallel And Distributed System, Security and Encryption, Web | Desktop Application",
    "Cloud Computing, Data Mining, Security and Encryption",
    "Cloud Computing, Data Mining, Security and Encryption, Web | Desktop Application",
    "Cloud Computing, Data Mining, Parallel And Distributed System, Security and Encryption, Web | Desktop Application",
    "Cloud Computing, Security and Encryption",
    "Image Processing, Security and Encryption",
    "Image Processing, AI, Security and Encryption",
    "IoT, Image Processing, Security and Encryption",
    "Security and Encryption",
    "Sensor, AI, Security and Encryption",
    "Security and Encryption, Sensor, Web | Desktop Application",
    "Security and Encryption, Web | Desktop Application",
    "Android Mobile Development, Security and Encryption",
    "Android Mobile Development, Security and Encryption, Web | Desktop Application",
    "Networking, Parallel And Distributed System, Security and Encryption, Web | Desktop Application",
    "Multimedia, Security and Encryption, Web | Desktop Application",
    "Multimedia, Security and Encryption",
  ],
  "Mobile Development": [
    "Android Mobile Development, AI, Web | Desktop Application",
    "Android Mobile Development",
    "Android Mobile Development, Machine Learning",
    "Android Mobile Development, Security and Encryption",
    "IoT, Android Mobile Development, Web | Desktop Application",
    "Mobile App Development",
    "Mobile App",
    "Mobile Development",
    "Mobile",
  ],
  "Web Development": [
    "AI, Web | Desktop Application",
    "Cloud Computing, Security and Encryption, Web | Desktop Application",
    "Cloud Computing, Networking, Parallel And Distributed System, Security and Encryption, Web | Desktop Application",
    "Cloud Computing, Web | Desktop Application",
    "IoT, AI, Web | Desktop Application",
    "IoT, Cloud Computing, Web | Desktop Application",
    "IoT, Android Mobile Development, Web | Desktop Application",
    "Web | Desktop Application",
    "Image Processing, AI, Web | Desktop Application",
    "Sensor, AI, Web | Desktop Application",
    "GPS-GSM, Sensor, Web | Desktop Application",
    "AI, Sensor, Web | Desktop Application",
    "Security and Encryption, Sensor, Web | Desktop Application",
    "Security and Encryption, Web | Desktop Application",
    "Networking, Parallel And Distributed System, Security and Encryption, Web | Desktop Application",
    "Multimedia, Security and Encryption, Web | Desktop Application",
    "Web Development",
  ],
  "GPS-GSM and Sensor": [
    "GPS-GSM",
    "IoT, Sensor, GPS-GSM",
    "GPS-GSM, Sensor, Web | Desktop Application",
    "Sensor, AI, Web | Desktop Application",
    "Sensor, AI, Security and Encryption",
    "Security and Encryption, Sensor, Web | Desktop Application",
  ],
  Healthcare: ["Healthcare, Data Science", "Healthcare", "Healthcare/Medical"],
  Miscellaneous: [
    "Data mining, Security and Encryption, Web | Desktop Application",
    "Non-Profit",
    "Education, Data Structures",
    "Education",
    "Sports Management",
    "Operations Management",
    "Law Enforcement",
    "HR Tech",
    "Agriculture",
    "Agriculture Technology",
    "Sports",
    "Technology",
    "Enterprise Software",
    "Fintech",
    "Mobile",
  ],
};
