const technicalSkillsOptions = [
    // Programming Languages
    "JavaScript",
    "Python",
    "Java",
    "C#",
    "C++",
    "PHP",
    "Ruby",
    "TypeScript",
    "Swift",
    "Kotlin",
    "Go",
    "Rust",
    "Scala",
    "Objective-C",
    "R",
    "Perl",
    "Haskell",
    "Shell Scripting",
    "Dart",
    "Elixir",
  
    // Web Development
    "HTML",
    "CSS",
    "Sass",
    "Bootstrap",
    "Tailwind CSS",
    "React.js",
    "Angular",
    "Vue.js",
    "Next.js",
    "Nuxt.js",
    "Ember.js",
    "jQuery",
    "Webpack",
    "Gulp",
    "Grunt",
  
    // Backend Development
    "Node.js",
    "Express.js",
    "Django",
    "Flask",
    "Ruby on Rails",
    "Laravel",
    "Spring Boot",
    "ASP.NET Core",
    "GraphQL",
    "RESTful APIs",
    "Microservices",
    "Serverless Architecture",
    "Firebase",
    "NestJS",
  
    // Databases
    "MySQL",
    "PostgreSQL",
    "SQLite",
    "MongoDB",
    "Redis",
    "Cassandra",
    "Elasticsearch",
    "Oracle Database",
    "Microsoft SQL Server",
    "MariaDB",
    "Firebase Realtime Database",
    "DynamoDB",
    "Couchbase",
    "Neo4j",
  
    // DevOps & Infrastructure
    "Docker",
    "Kubernetes",
    "CI/CD",
    "Jenkins",
    "GitLab CI",
    "CircleCI",
    "Ansible",
    "Terraform",
    "AWS",
    "Azure",
    "Google Cloud Platform",
    "OpenStack",
    "Linux System Administration",
    "Nginx",
    "Apache",
    "Vagrant",
    "CloudFormation",
    "Prometheus",
    "Grafana",
    "Elastic Stack (ELK)",
  
    // Mobile Development
    "React Native",
    "Flutter",
    "Xamarin",
    "Ionic",
    "Swift",
    "Objective-C",
    "Kotlin",
    "Java (Android Development)",
    "Unity3D (Mobile Games)",
    "ARKit",
    "ARCore",
  
    // Data Science & Machine Learning
    "Pandas",
    "NumPy",
    "Matplotlib",
    "Seaborn",
    "SciPy",
    "Scikit-learn",
    "TensorFlow",
    "Keras",
    "PyTorch",
    "Natural Language Processing (NLP)",
    "OpenCV",
    "Jupyter",
    "Hadoop",
    "Spark",
    "Dask",
    "AWS SageMaker",
    "Google Cloud AI",
    "Azure Machine Learning",
    "BigQuery",
    "Data Visualization",
    "Data Warehousing",
  
    // Cybersecurity
    "Penetration Testing",
    "Ethical Hacking",
    "Network Security",
    "Encryption",
    "Firewalls",
    "Intrusion Detection Systems (IDS)",
    "SIEM (Security Information and Event Management)",
    "OWASP",
    "SOC (Security Operations Center)",
    "Kali Linux",
    "Wireshark",
    "Metasploit",
    "Nmap",
    "Burp Suite",
    "Cloud Security",
    "Zero Trust Architecture",
  
    // Blockchain
    "Solidity",
    "Ethereum",
    "Hyperledger",
    "Smart Contracts",
    "Web3.js",
    "Truffle",
    "Hardhat",
    "Chainlink",
    "Cryptography",
    "DApps (Decentralized Applications)",
  
    // Artificial Intelligence
    "Machine Learning",
    "Deep Learning",
    "Reinforcement Learning",
    "Natural Language Processing",
    "Computer Vision",
    "AI Ethics",
    "Generative AI",
    "GPT Models",
    "BERT",
    "AI Model Deployment",
    "Robotic Process Automation (RPA)",
    "OpenAI API",
    "AutoML",
    "Edge AI",
  
    // Game Development
    "Unity3D",
    "Unreal Engine",
    "Cocos2d",
    "Godot",
    "Game Physics",
    "Shader Programming",
    "3D Modeling",
    "Blender",
    "Maya",
    "Substance Painter",
    "Game AI",
    "Virtual Reality (VR)",
    "Augmented Reality (AR)",
  
    // Other Tools & Technologies
    "Git",
    "GitHub",
    "Bitbucket",
    "JIRA",
    "Trello",
    "Confluence",
    "Slack",
    "VS Code",
    "Atom",
    "Eclipse",
    "IntelliJ IDEA",
    "PyCharm",
    "Sublime Text",
    "Postman",
    "Swagger",
    "Figma",
    "Adobe XD",
    "Zeplin",
    "Togaf",
    "Agile Methodologies",
    "Scrum",
    "Kanban",
    "Test-Driven Development (TDD)",
    "Behavior-Driven Development (BDD)",
    "Continuous Integration (CI)",
    "Continuous Deployment (CD)",
    "Unit Testing",
    "Integration Testing",
    "End-to-End Testing",
    "Mocha",
    "Chai",
    "Jest",
    "Selenium",
    "Cypress",
    "Puppeteer",
];

export default technicalSkillsOptions
  