export const users = [
  {
    id: 1,
    name: "Karim Haddad",
    // profile_picture: "https://i.pravatar.cc/150?img=1",
    bio: "Full-stack Web Developer with expertise in modern JavaScript frameworks.",
    general_field: "Software Engineering",
    skills: ["JavaScript", "React", "Node.js"],
    linkedin_profile: "https://linkedin.com/in/karimhaddad",
    is_following: false,
    followers_count: 2,
    userProjects: [
      {
        id: 1,
        title: "Personal Portfolio",
        description: "A modern portfolio website built using React and Node.js.",
        status: "Completed",
        url: "https://karimhaddad.com",
        technologies: ["React", "Node.js", "CSS"],
        start_date: "2021-01-01",
        end_date: "2021-03-01",
      },
    ],
  },
  {
    id: 2,
    name: "Maya Abou Hassan",
    // profile_picture: "https://i.pravatar.cc/150?img=2",
    bio: "Data Scientist specializing in machine learning and predictive analytics.",
    general_field: "Data Science",
    skills: ["Python", "TensorFlow", "Pandas"],
    linkedin_profile: "https://linkedin.com/in/mayaabouhassan",
    is_following: false,
    followers_count: 2,
    userProjects: [
      {
        id: 2,
        title: "Customer Churn Prediction",
        description:
          "Built a machine learning model to predict customer churn for a telecom company.",
        status: "Ongoing",
        url: null,
        technologies: ["Python", "TensorFlow", "Pandas"],
        start_date: "2022-05-15",
        end_date: null,
      },
    ],
  },
  {
    id: 3,
    name: "Rami Fakhoury",
    // profile_picture: "https://i.pravatar.cc/150?img=3",
    bio: "Cloud Infrastructure Engineer focused on AWS and containerization.",
    general_field: "Cloud Engineering",
    skills: ["AWS", "Terraform", "Docker"],
    linkedin_profile: "https://linkedin.com/in/ramifakhoury",
    is_following: false,
    followers_count: 2,
    userProjects: [
      {
        id: 3,
        title: "Cloud Infrastructure Setup",
        description:
          "Implemented a cloud infrastructure for a startup using AWS and Terraform.",
        status: "Completed",
        url: null,
        technologies: ["AWS", "Terraform", "Docker"],
        start_date: "2021-09-01",
        end_date: "2022-01-10",
      },
    ],
  },
  {
    id: 4,
    name: "Lara Ghanem",
    // profile_picture: "https://i.pravatar.cc/150?img=4",
    bio: "Mobile Developer creating intuitive and performant cross-platform apps.",
    general_field: "Mobile Development",
    skills: ["Kotlin", "Swift", "Flutter"],
    linkedin_profile: "https://linkedin.com/in/sophiaghanem",
    is_following: false,
    followers_count: 2,
    userProjects: [
      {
        id: 4,
        title: "Fitness Tracking App",
        description:
          "Developed a cross-platform fitness tracking app using Flutter.",
        status: "Completed",
        url: "https://fitnessapp.com",
        technologies: ["Flutter", "Dart", "Firebase"],
        start_date: "2020-11-01",
        end_date: "2021-04-01",
      },
    ],
  },
  {
    id: 5,
    name: "Ahmad Nasrallah",
    // profile_picture: "https://i.pravatar.cc/150?img=5",
    bio: "Cybersecurity Analyst with a focus on network security and ethical hacking.",
    general_field: "Cybersecurity",
    skills: ["Penetration Testing", "Kali Linux", "Wireshark"],
    linkedin_profile: "https://linkedin.com/in/davidnasrallah",
    is_following: false,
    followers_count: 2,
    userProjects: [
      {
        id: 5,
        title: "Enterprise Security Audit",
        description:
          "Led a comprehensive network security audit for a large corporate client.",
        status: "Ongoing",
        url: null,
        technologies: ["Kali Linux", "Wireshark", "Nmap"],
        start_date: "2022-07-01",
        end_date: null,
      },
    ],
  },
  {
    id: 6,
    name: "Karim Haddad",
    // profile_picture: "https://i.pravatar.cc/150?img=1",
    bio: "Full-stack Web Developer with expertise in modern JavaScript frameworks.",
    general_field: "Software Engineering",
    skills: ["JavaScript", "React", "Node.js"],
    linkedin_profile: "https://linkedin.com/in/karimhaddad",
    is_following: false,
    followers_count: 2,
    userProjects: [
      {
        id: 1,
        title: "Personal Portfolio",
        description: "A modern portfolio website built using React and Node.js.",
        status: "Completed",
        url: "https://karimhaddad.com",
        technologies: ["React", "Node.js", "CSS"],
        start_date: "2021-01-01",
        end_date: "2021-03-01",
      },
    ],
  },
  {
    id: 7,
    name: "Maya Abou Hassan",
    // profile_picture: "https://i.pravatar.cc/150?img=2",
    bio: "Data Scientist specializing in machine learning and predictive analytics.",
    general_field: "Data Science",
    skills: ["Python", "TensorFlow", "Pandas"],
    linkedin_profile: "https://linkedin.com/in/mayaabouhassan",
    is_following: false,
    followers_count: 2,
    userProjects: [
      {
        id: 2,
        title: "Customer Churn Prediction",
        description:
          "Built a machine learning model to predict customer churn for a telecom company.",
        status: "Ongoing",
        url: null,
        technologies: ["Python", "TensorFlow", "Pandas"],
        start_date: "2022-05-15",
        end_date: null,
      },
    ],
  },
  {
    id: 8,
    name: "Rami Fakhoury",
    // profile_picture: "https://i.pravatar.cc/150?img=3",
    bio: "Cloud Infrastructure Engineer focused on AWS and containerization.",
    general_field: "Cloud Engineering",
    skills: ["AWS", "Terraform", "Docker"],
    linkedin_profile: "https://linkedin.com/in/ramifakhoury",
    is_following: false,
    followers_count: 2,
    userProjects: [
      {
        id: 3,
        title: "Cloud Infrastructure Setup",
        description:
          "Implemented a cloud infrastructure for a startup using AWS and Terraform.",
        status: "Completed",
        url: null,
        technologies: ["AWS", "Terraform", "Docker"],
        start_date: "2021-09-01",
        end_date: "2022-01-10",
      },
    ],
  },
  {
    id: 9,
    name: "Lara Ghanem",
    // profile_picture: "https://i.pravatar.cc/150?img=4",
    bio: "Mobile Developer creating intuitive and performant cross-platform apps.",
    general_field: "Mobile Development",
    skills: ["Kotlin", "Swift", "Flutter"],
    linkedin_profile: "https://linkedin.com/in/sophiaghanem",
    is_following: false,
    followers_count: 2,
    userProjects: [
      {
        id: 4,
        title: "Fitness Tracking App",
        description:
          "Developed a cross-platform fitness tracking app using Flutter.",
        status: "Completed",
        url: "https://fitnessapp.com",
        technologies: ["Flutter", "Dart", "Firebase"],
        start_date: "2020-11-01",
        end_date: "2021-04-01",
      },
    ],
  },
  {
    id: 10,
    name: "Ahmad Nasrallah",
    // profile_picture: "https://i.pravatar.cc/150?img=5",
    bio: "Cybersecurity Analyst with a focus on network security and ethical hacking.",
    general_field: "Cybersecurity",
    skills: ["Penetration Testing", "Kali Linux", "Wireshark"],
    linkedin_profile: "https://linkedin.com/in/davidnasrallah",
    is_following: false,
    followers_count: 2,
    userProjects: [
      {
        id: 5,
        title: "Enterprise Security Audit",
        description:
          "Led a comprehensive network security audit for a large corporate client.",
        status: "Ongoing",
        url: null,
        technologies: ["Kali Linux", "Wireshark", "Nmap"],
        start_date: "2022-07-01",
        end_date: null,
      },
    ],
  },
];
